remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Recipes Analysis]
description: [DSC80 Project3 - Analysis on Minutes to prepare vs. Average rating of recipes]
author: [Zhirui Xia, Leica Shen]